export { default as HeroSlider } from './HeroSlider';
export { default as AboutSection } from './AboutSection';
export { default as ProfileVideoSection } from './ProfileVideoSection';
export { default as CabinetHistorySection } from './CabinetHistorySection';
export { default as ContactUsSection } from './ContactUsSection';
export { default as StatsBar } from './StatsBar';
export { default as PillarsSection } from './PillarsSection';
export { default as GallerySection } from './GallerySection';
export { default as QuickAccessCTA } from './QuickAccessCTA';
